// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGItCtz3wpUiQy3Jatp-3IV0FA5Fo1XGw',
    appId: '1:1001426845095:web:0d9529e1790ef24b4a0a82',
    messagingSenderId: '1001426845095',
    projectId: 'kregulechubdev',
    authDomain: 'kregulechubdev.firebaseapp.com',
    databaseURL: 'https://kregulechubdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kregulechubdev.appspot.com',
    measurementId: 'G-593YPRXTKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwrswR1_Woxmd0xOYFcxky1zDRBOKiyg',
    appId: '1:1001426845095:android:5273dd7f244f5a9b4a0a82',
    messagingSenderId: '1001426845095',
    projectId: 'kregulechubdev',
    databaseURL: 'https://kregulechubdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kregulechubdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjLBsmchrXeeMpXR7F0SaEajni_fmdxo',
    appId: '1:1001426845095:ios:1334c6e23cf4b2614a0a82',
    messagingSenderId: '1001426845095',
    projectId: 'kregulechubdev',
    databaseURL: 'https://kregulechubdev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kregulechubdev.appspot.com',
    iosBundleId: 'com.example.kregulecHub',
  );
}
